name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install torch torchvision torchaudio
        pip install transformers[torch] accelerate datasets
        pip install scikit-learn pandas datasets numpy

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run training
      run: python scripts/train.py

    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: ./data/results/final_model

    - name: Download model
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: ./data/results/final_model

    - name: Run evaluation
      run: python scripts/evaluate_and_save.py
