name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run training
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scripts/train.py
      
      - name: Run evaluation and push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scripts/evaluate_and_save.py
      
      - name: Run monitoring
        run: python scripts/monitor.py
      
      - name: Upload monitoring log
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-log
          path: ./data/monitoring/metrics_log.json
          if-no-files-found: ignore

      - name: Salva monitoring log nel repo
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git pull origin main
          mkdir -p data/monitoring
          git add data/monitoring/metrics_log.json
          git commit -m "update monitoring log [skip ci]" || echo "nessuna modifica"
          git push

